# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_analysis_type_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(571, 195)
        Dialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.analysisGroupBox = QtWidgets.QGroupBox(Dialog)
        self.analysisGroupBox.setObjectName("analysisGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.analysisGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.knee_oa_radioButton = QtWidgets.QRadioButton(self.analysisGroupBox)
        self.knee_oa_radioButton.setChecked(True)
        self.knee_oa_radioButton.setObjectName("knee_oa_radioButton")
        self.verticalLayout.addWidget(self.knee_oa_radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.analysisGroupBox)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.label_2 = QtWidgets.QLabel(self.analysisGroupBox)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.splitter = QtWidgets.QSplitter(self.analysisGroupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setObjectName("label")
        self.alpha_comboBox = QtWidgets.QComboBox(self.splitter)
        self.alpha_comboBox.setEditable(True)
        self.alpha_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.alpha_comboBox.setObjectName("alpha_comboBox")
        self.alpha_comboBox.addItem("")
        self.alpha_comboBox.setItemText(0, "0.005")
        self.alpha_comboBox.addItem("")
        self.alpha_comboBox.setItemText(1, "0.01")
        self.alpha_comboBox.addItem("")
        self.alpha_comboBox.setItemText(2, "0.05")
        self.alpha_comboBox.addItem("")
        self.alpha_comboBox.setItemText(3, "0.1")
        self.verticalLayout.addWidget(self.splitter)
        self.gridLayout.addWidget(self.analysisGroupBox, 0, 0, 1, 1)
        self.SideGroupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.SideGroupBox_2.setObjectName("SideGroupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SideGroupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.moments_radioButton = QtWidgets.QRadioButton(self.SideGroupBox_2)
        self.moments_radioButton.setChecked(True)
        self.moments_radioButton.setAutoExclusive(True)
        self.moments_radioButton.setObjectName("moments_radioButton")
        self.verticalLayout_3.addWidget(self.moments_radioButton)
        self.kinematics_radioButton = QtWidgets.QRadioButton(self.SideGroupBox_2)
        self.kinematics_radioButton.setAutoExclusive(True)
        self.kinematics_radioButton.setObjectName("kinematics_radioButton")
        self.verticalLayout_3.addWidget(self.kinematics_radioButton)
        self.kinematics_radioButton_2 = QtWidgets.QRadioButton(self.SideGroupBox_2)
        self.kinematics_radioButton_2.setEnabled(False)
        self.kinematics_radioButton_2.setAutoExclusive(True)
        self.kinematics_radioButton_2.setObjectName("kinematics_radioButton_2")
        self.verticalLayout_3.addWidget(self.kinematics_radioButton_2)
        self.gridLayout.addWidget(self.SideGroupBox_2, 0, 2, 1, 1)
        self.SideGroupBox = QtWidgets.QGroupBox(Dialog)
        self.SideGroupBox.setObjectName("SideGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SideGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rt_side_checkBox = QtWidgets.QCheckBox(self.SideGroupBox)
        self.rt_side_checkBox.setChecked(True)
        self.rt_side_checkBox.setObjectName("rt_side_checkBox")
        self.verticalLayout_2.addWidget(self.rt_side_checkBox)
        self.lt_side_checkBox = QtWidgets.QCheckBox(self.SideGroupBox)
        self.lt_side_checkBox.setChecked(True)
        self.lt_side_checkBox.setObjectName("lt_side_checkBox")
        self.verticalLayout_2.addWidget(self.lt_side_checkBox)
        self.gridLayout.addWidget(self.SideGroupBox, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(31, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 5)

        self.retranslateUi(Dialog)
        self.alpha_comboBox.setCurrentIndex(2)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.analysisGroupBox.setTitle(_translate("Dialog", "Analysis"))
        self.knee_oa_radioButton.setText(_translate("Dialog", "Knee OA"))
        self.radioButton_2.setText(_translate("Dialog", "Knee Ambutation"))
        self.label.setText(_translate("Dialog", "Alpha"))
        self.SideGroupBox_2.setTitle(_translate("Dialog", "Show"))
        self.moments_radioButton.setText(_translate("Dialog", "Moments"))
        self.kinematics_radioButton.setText(_translate("Dialog", "Kinematics"))
        self.kinematics_radioButton_2.setText(_translate("Dialog", "Spatiotemporal"))
        self.SideGroupBox.setTitle(_translate("Dialog", "Side"))
        self.rt_side_checkBox.setText(_translate("Dialog", "Right Side"))
        self.lt_side_checkBox.setText(_translate("Dialog", "Left Side"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

