# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_colormap_chooser.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_colorMapChooser(object):
    def setupUi(self, colorMapChooser):
        colorMapChooser.setObjectName("colorMapChooser")
        colorMapChooser.resize(437, 539)
        self.gridLayout = QtWidgets.QGridLayout(colorMapChooser)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(colorMapChooser)
        self.toolBox.setObjectName("toolBox")
        self.Scalarcomponents = QtWidgets.QWidget()
        self.Scalarcomponents.setGeometry(QtCore.QRect(0, 0, 417, 436))
        self.Scalarcomponents.setObjectName("Scalarcomponents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Scalarcomponents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_7)
        self.label_5 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.min_value_spinbox = QtWidgets.QSpinBox(self.Scalarcomponents)
        self.min_value_spinbox.setProperty("value", 1)
        self.min_value_spinbox.setObjectName("min_value_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.min_value_spinbox)
        self.label_6 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.max_value_spinbox = QtWidgets.QSpinBox(self.Scalarcomponents)
        self.max_value_spinbox.setProperty("value", 4)
        self.max_value_spinbox.setObjectName("max_value_spinbox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_value_spinbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_8 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_8)
        self.label_11 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.label = QtWidgets.QLabel(self.Scalarcomponents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label)
        self.num_levels_spinBox = QtWidgets.QSpinBox(self.Scalarcomponents)
        self.num_levels_spinBox.setMinimum(3)
        self.num_levels_spinBox.setMaximum(20)
        self.num_levels_spinBox.setProperty("value", 4)
        self.num_levels_spinBox.setObjectName("num_levels_spinBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.num_levels_spinBox)
        self.label_2 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.colormap_name_comboBox = QtWidgets.QComboBox(self.Scalarcomponents)
        self.colormap_name_comboBox.setObjectName("colormap_name_comboBox")
        self.colormap_name_comboBox.addItem("")
        self.colormap_name_comboBox.setItemText(0, "coolwarm")
        self.colormap_name_comboBox.addItem("")
        self.colormap_name_comboBox.setItemText(1, "jet")
        self.colormap_name_comboBox.addItem("")
        self.colormap_name_comboBox.setItemText(2, "viridis")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.colormap_name_comboBox)
        self.min_value_spinbox_2 = QtWidgets.QSpinBox(self.Scalarcomponents)
        self.min_value_spinbox_2.setProperty("value", 1)
        self.min_value_spinbox_2.setObjectName("min_value_spinbox_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.min_value_spinbox_2)
        self.label_9 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.Scalarcomponents)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.max_value_spinbox_2 = QtWidgets.QSpinBox(self.Scalarcomponents)
        self.max_value_spinbox_2.setProperty("value", 10)
        self.max_value_spinbox_2.setObjectName("max_value_spinbox_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.max_value_spinbox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.gridLayout_2.addLayout(self.formLayout, 1, 0, 1, 1)
        self.colormap_legend = LegendMplCanvas(self.Scalarcomponents)
        self.colormap_legend.setObjectName("colormap_legend")
        self.gridLayout_2.addWidget(self.colormap_legend, 1, 1, 2, 1)
        self.checkBox = QtWidgets.QCheckBox(self.Scalarcomponents)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 5)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.Scalarcomponents, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 272, 137))
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_2)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_2.setMinimum(3)
        self.spinBox_2.setMaximum(20)
        self.spinBox_2.setProperty("value", 4)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_3.addWidget(self.spinBox_2, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_2.setCurrentText("Jet")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 6, 0, 1, 1)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(colorMapChooser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.label_5.setBuddy(self.min_value_spinbox)
        self.label_6.setBuddy(self.max_value_spinbox)
        self.label.setBuddy(self.num_levels_spinBox)
        self.label_2.setBuddy(self.colormap_name_comboBox)
        self.label_10.setBuddy(self.max_value_spinbox)

        self.retranslateUi(colorMapChooser)
        self.toolBox.setCurrentIndex(0)
        self.colormap_name_comboBox.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(0)
        self.buttonBox.accepted.connect(colorMapChooser.accept)
        self.buttonBox.rejected.connect(colorMapChooser.reject)
        self.colormap_name_comboBox.currentIndexChanged['int'].connect(colorMapChooser.update_legend)
        self.num_levels_spinBox.valueChanged['int'].connect(colorMapChooser.update_legend)
        QtCore.QMetaObject.connectSlotsByName(colorMapChooser)
        colorMapChooser.setTabOrder(self.min_value_spinbox, self.max_value_spinbox)
        colorMapChooser.setTabOrder(self.max_value_spinbox, self.num_levels_spinBox)
        colorMapChooser.setTabOrder(self.num_levels_spinBox, self.colormap_name_comboBox)
        colorMapChooser.setTabOrder(self.colormap_name_comboBox, self.checkBox)
        colorMapChooser.setTabOrder(self.checkBox, self.comboBox_2)
        colorMapChooser.setTabOrder(self.comboBox_2, self.checkBox_2)
        colorMapChooser.setTabOrder(self.checkBox_2, self.spinBox_2)

    def retranslateUi(self, colorMapChooser):
        _translate = QtCore.QCoreApplication.translate
        colorMapChooser.setWindowTitle(_translate("colorMapChooser", "Colormap Options"))
        self.label_7.setText(_translate("colorMapChooser", "Individual compenents"))
        self.label_5.setText(_translate("colorMapChooser", "Min Value"))
        self.label_6.setText(_translate("colorMapChooser", "Max Value"))
        self.label_8.setText(_translate("colorMapChooser", "Three dimensional analysis"))
        self.label_11.setText(_translate("colorMapChooser", "Legend Colors"))
        self.label.setText(_translate("colorMapChooser", "Number of levels"))
        self.label_2.setText(_translate("colorMapChooser", "Colormap Name"))
        self.label_9.setText(_translate("colorMapChooser", "Min Value"))
        self.label_10.setText(_translate("colorMapChooser", "Max Value"))
        self.checkBox.setText(_translate("colorMapChooser", "Different colors for positive and negative values"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Scalarcomponents), _translate("colorMapChooser", "Page 1"))
        self.checkBox_2.setText(_translate("colorMapChooser", "Different colors for positive and negative values"))
        self.label_4.setText(_translate("colorMapChooser", "Number of levels"))
        self.label_3.setText(_translate("colorMapChooser", "Colormap Name"))
        self.comboBox_2.setItemText(0, _translate("colorMapChooser", "Jet"))
        self.comboBox_2.setItemText(1, _translate("colorMapChooser", "viridis"))
        self.comboBox_2.setItemText(2, _translate("colorMapChooser", "Coolhot"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("colorMapChooser", "Page 2"))

from spmclient.ui.gui.xml.mplcanvas import LegendMplCanvas

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    colorMapChooser = QtWidgets.QDialog()
    ui = Ui_colorMapChooser()
    ui.setupUi(colorMapChooser)
    colorMapChooser.show()
    sys.exit(app.exec_())

