# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_gait_analysis_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_GaitAnalysisWindow(object):
    def setupUi(self, ui_GaitAnalysisWindow):
        ui_GaitAnalysisWindow.setObjectName("ui_GaitAnalysisWindow")
        ui_GaitAnalysisWindow.setWindowModality(QtCore.Qt.WindowModal)
        ui_GaitAnalysisWindow.resize(1489, 771)
        ui_GaitAnalysisWindow.setProperty("visible_hip", False)
        ui_GaitAnalysisWindow.setProperty("visible_knee", False)
        ui_GaitAnalysisWindow.setProperty("visible_ankle", False)
        ui_GaitAnalysisWindow.setProperty("show_colormap", False)
        self.centralwidget = QtWidgets.QWidget(ui_GaitAnalysisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget_gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralwidget_gridLayout.setObjectName("centralwidget_gridLayout")
        self.three_columns_layout = QtWidgets.QGridLayout()
        self.three_columns_layout.setSpacing(0)
        self.three_columns_layout.setObjectName("three_columns_layout")
        self.widget_lt_side = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_lt_side.sizePolicy().hasHeightForWidth())
        self.widget_lt_side.setSizePolicy(sizePolicy)
        self.widget_lt_side.setObjectName("widget_lt_side")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_lt_side)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget_lt_side)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 2, 1, 1)
        self.stackedWidget21L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget21L.sizePolicy().hasHeightForWidth())
        self.stackedWidget21L.setSizePolicy(sizePolicy)
        self.stackedWidget21L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget21L.setObjectName("stackedWidget21L")
        self.mosecanvas21L = MplCanvas()
        self.mosecanvas21L.setObjectName("mosecanvas21L")
        self.stackedWidget21L.addWidget(self.mosecanvas21L)
        self.spm1dcanvas21L = MplCanvas()
        self.spm1dcanvas21L.setObjectName("spm1dcanvas21L")
        self.stackedWidget21L.addWidget(self.spm1dcanvas21L)
        self.gridLayout_3.addWidget(self.stackedWidget21L, 10, 1, 1, 1)
        self.joint2L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint2L.sizePolicy().hasHeightForWidth())
        self.joint2L.setSizePolicy(sizePolicy)
        self.joint2L.setMinimumSize(QtCore.QSize(200, 30))
        self.joint2L.setObjectName("joint2L")
        self.gridLayout_3.addWidget(self.joint2L, 11, 0, 1, 2)
        self.stackedWidget12L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget12L.sizePolicy().hasHeightForWidth())
        self.stackedWidget12L.setSizePolicy(sizePolicy)
        self.stackedWidget12L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget12L.setObjectName("stackedWidget12L")
        self.mosecanvas12L = MplCanvas()
        self.mosecanvas12L.setObjectName("mosecanvas12L")
        self.stackedWidget12L.addWidget(self.mosecanvas12L)
        self.spm1dcanvas12L = MplCanvas()
        self.spm1dcanvas12L.setObjectName("spm1dcanvas12L")
        self.stackedWidget12L.addWidget(self.spm1dcanvas12L)
        self.gridLayout_3.addWidget(self.stackedWidget12L, 6, 2, 1, 1)
        self.stackedWidget01L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget01L.sizePolicy().hasHeightForWidth())
        self.stackedWidget01L.setSizePolicy(sizePolicy)
        self.stackedWidget01L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget01L.setObjectName("stackedWidget01L")
        self.mosecanvas01L = MplCanvas()
        self.mosecanvas01L.setObjectName("mosecanvas01L")
        self.stackedWidget01L.addWidget(self.mosecanvas01L)
        self.spm1dcanvas01L = MplCanvas()
        self.spm1dcanvas01L.setObjectName("spm1dcanvas01L")
        self.stackedWidget01L.addWidget(self.spm1dcanvas01L)
        self.gridLayout_3.addWidget(self.stackedWidget01L, 2, 1, 1, 1)
        self.stackedWidget02L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget02L.sizePolicy().hasHeightForWidth())
        self.stackedWidget02L.setSizePolicy(sizePolicy)
        self.stackedWidget02L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget02L.setObjectName("stackedWidget02L")
        self.mosecanvas02L = MplCanvas()
        self.mosecanvas02L.setObjectName("mosecanvas02L")
        self.stackedWidget02L.addWidget(self.mosecanvas02L)
        self.spm1dcanvas02L = MplCanvas()
        self.spm1dcanvas02L.setObjectName("spm1dcanvas02L")
        self.stackedWidget02L.addWidget(self.spm1dcanvas02L)
        self.gridLayout_3.addWidget(self.stackedWidget02L, 2, 2, 1, 1)
        self.joint0L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint0L.sizePolicy().hasHeightForWidth())
        self.joint0L.setSizePolicy(sizePolicy)
        self.joint0L.setMinimumSize(QtCore.QSize(200, 30))
        self.joint0L.setAutoFillBackground(True)
        self.joint0L.setObjectName("joint0L")
        self.gridLayout_3.addWidget(self.joint0L, 3, 0, 1, 2)
        self.stackedWidget00L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.stackedWidget00L.sizePolicy().hasHeightForWidth())
        self.stackedWidget00L.setSizePolicy(sizePolicy)
        self.stackedWidget00L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget00L.setObjectName("stackedWidget00L")
        self.mosecanvas00L = MplCanvas()
        self.mosecanvas00L.setObjectName("mosecanvas00L")
        self.stackedWidget00L.addWidget(self.mosecanvas00L)
        self.spm1dcanvas00L = MplCanvas()
        self.spm1dcanvas00L.setObjectName("spm1dcanvas00L")
        self.stackedWidget00L.addWidget(self.spm1dcanvas00L)
        self.gridLayout_3.addWidget(self.stackedWidget00L, 2, 0, 1, 1)
        self.stackedWidget22L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget22L.sizePolicy().hasHeightForWidth())
        self.stackedWidget22L.setSizePolicy(sizePolicy)
        self.stackedWidget22L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget22L.setObjectName("stackedWidget22L")
        self.mosecanvas22L = MplCanvas()
        self.mosecanvas22L.setObjectName("mosecanvas22L")
        self.stackedWidget22L.addWidget(self.mosecanvas22L)
        self.spm1dcanvas22L = MplCanvas()
        self.spm1dcanvas22L.setObjectName("spm1dcanvas22L")
        self.stackedWidget22L.addWidget(self.spm1dcanvas22L)
        self.gridLayout_3.addWidget(self.stackedWidget22L, 10, 2, 1, 1)
        self.joint1L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint1L.sizePolicy().hasHeightForWidth())
        self.joint1L.setSizePolicy(sizePolicy)
        self.joint1L.setMinimumSize(QtCore.QSize(200, 30))
        self.joint1L.setObjectName("joint1L")
        self.gridLayout_3.addWidget(self.joint1L, 7, 0, 1, 2)
        self.stackedWidget10L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.stackedWidget10L.sizePolicy().hasHeightForWidth())
        self.stackedWidget10L.setSizePolicy(sizePolicy)
        self.stackedWidget10L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget10L.setObjectName("stackedWidget10L")
        self.mosecanvas10L = MplCanvas()
        self.mosecanvas10L.setObjectName("mosecanvas10L")
        self.stackedWidget10L.addWidget(self.mosecanvas10L)
        self.spm1dcanvas10L = MplCanvas()
        self.spm1dcanvas10L.setObjectName("spm1dcanvas10L")
        self.stackedWidget10L.addWidget(self.spm1dcanvas10L)
        self.gridLayout_3.addWidget(self.stackedWidget10L, 6, 0, 1, 1)
        self.stackedWidget11L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget11L.sizePolicy().hasHeightForWidth())
        self.stackedWidget11L.setSizePolicy(sizePolicy)
        self.stackedWidget11L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget11L.setObjectName("stackedWidget11L")
        self.mosecanvas11L = MplCanvas()
        self.mosecanvas11L.setObjectName("mosecanvas11L")
        self.stackedWidget11L.addWidget(self.mosecanvas11L)
        self.spm1dcanvas11L = MplCanvas()
        self.spm1dcanvas11L.setObjectName("spm1dcanvas11L")
        self.stackedWidget11L.addWidget(self.spm1dcanvas11L)
        self.gridLayout_3.addWidget(self.stackedWidget11L, 6, 1, 1, 1)
        self.stackedWidget20L = QtWidgets.QStackedWidget(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.stackedWidget20L.sizePolicy().hasHeightForWidth())
        self.stackedWidget20L.setSizePolicy(sizePolicy)
        self.stackedWidget20L.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget20L.setObjectName("stackedWidget20L")
        self.mosecanvas20L = MplCanvas()
        self.mosecanvas20L.setObjectName("mosecanvas20L")
        self.stackedWidget20L.addWidget(self.mosecanvas20L)
        self.spm1dcanvas20L = MplCanvas()
        self.spm1dcanvas20L.setObjectName("spm1dcanvas20L")
        self.stackedWidget20L.addWidget(self.spm1dcanvas20L)
        self.gridLayout_3.addWidget(self.stackedWidget20L, 10, 0, 1, 1)
        self.datacanvas10L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.datacanvas10L.sizePolicy().hasHeightForWidth())
        self.datacanvas10L.setSizePolicy(sizePolicy)
        self.datacanvas10L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas10L.setObjectName("datacanvas10L")
        self.gridLayout_3.addWidget(self.datacanvas10L, 5, 0, 1, 1)
        self.datacanvas21L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas21L.sizePolicy().hasHeightForWidth())
        self.datacanvas21L.setSizePolicy(sizePolicy)
        self.datacanvas21L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas21L.setObjectName("datacanvas21L")
        self.gridLayout_3.addWidget(self.datacanvas21L, 9, 1, 1, 1)
        self.datacanvas11L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas11L.sizePolicy().hasHeightForWidth())
        self.datacanvas11L.setSizePolicy(sizePolicy)
        self.datacanvas11L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas11L.setObjectName("datacanvas11L")
        self.gridLayout_3.addWidget(self.datacanvas11L, 5, 1, 1, 1)
        self.datacanvas22L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas22L.sizePolicy().hasHeightForWidth())
        self.datacanvas22L.setSizePolicy(sizePolicy)
        self.datacanvas22L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas22L.setObjectName("datacanvas22L")
        self.gridLayout_3.addWidget(self.datacanvas22L, 9, 2, 1, 1)
        self.datacanvas12L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas12L.sizePolicy().hasHeightForWidth())
        self.datacanvas12L.setSizePolicy(sizePolicy)
        self.datacanvas12L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas12L.setObjectName("datacanvas12L")
        self.gridLayout_3.addWidget(self.datacanvas12L, 5, 2, 1, 1)
        self.datacanvas20L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.datacanvas20L.sizePolicy().hasHeightForWidth())
        self.datacanvas20L.setSizePolicy(sizePolicy)
        self.datacanvas20L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas20L.setObjectName("datacanvas20L")
        self.gridLayout_3.addWidget(self.datacanvas20L, 9, 0, 1, 1)
        self.datacanvas02L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas02L.sizePolicy().hasHeightForWidth())
        self.datacanvas02L.setSizePolicy(sizePolicy)
        self.datacanvas02L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas02L.setObjectName("datacanvas02L")
        self.gridLayout_3.addWidget(self.datacanvas02L, 1, 2, 1, 1)
        self.datacanvas01L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas01L.sizePolicy().hasHeightForWidth())
        self.datacanvas01L.setSizePolicy(sizePolicy)
        self.datacanvas01L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas01L.setObjectName("datacanvas01L")
        self.gridLayout_3.addWidget(self.datacanvas01L, 1, 1, 1, 1)
        self.datacanvas00L = MplCanvas(self.widget_lt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.datacanvas00L.sizePolicy().hasHeightForWidth())
        self.datacanvas00L.setSizePolicy(sizePolicy)
        self.datacanvas00L.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas00L.setObjectName("datacanvas00L")
        self.gridLayout_3.addWidget(self.datacanvas00L, 1, 0, 1, 1)
        self.label_addL = QtWidgets.QLabel(self.widget_lt_side)
        self.label_addL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_addL.setObjectName("label_addL")
        self.gridLayout_3.addWidget(self.label_addL, 0, 1, 1, 1)
        self.label_rotL = QtWidgets.QLabel(self.widget_lt_side)
        self.label_rotL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rotL.setObjectName("label_rotL")
        self.gridLayout_3.addWidget(self.label_rotL, 0, 2, 1, 1)
        self.label_flexL = QtWidgets.QLabel(self.widget_lt_side)
        self.label_flexL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flexL.setObjectName("label_flexL")
        self.gridLayout_3.addWidget(self.label_flexL, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_lt_side)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 8, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.three_columns_layout.addWidget(self.widget_lt_side, 0, 2, 3, 1)
        self.widget_rt_side = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_rt_side.sizePolicy().hasHeightForWidth())
        self.widget_rt_side.setSizePolicy(sizePolicy)
        self.widget_rt_side.setObjectName("widget_rt_side")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_rt_side)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget00R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget00R.sizePolicy().hasHeightForWidth())
        self.stackedWidget00R.setSizePolicy(sizePolicy)
        self.stackedWidget00R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget00R.setObjectName("stackedWidget00R")
        self.mosecanvas00R = MplCanvas()
        self.mosecanvas00R.setObjectName("mosecanvas00R")
        self.stackedWidget00R.addWidget(self.mosecanvas00R)
        self.spm1dcanvas00R = MplCanvas()
        self.spm1dcanvas00R.setObjectName("spm1dcanvas00R")
        self.stackedWidget00R.addWidget(self.spm1dcanvas00R)
        self.gridLayout_5.addWidget(self.stackedWidget00R, 2, 0, 1, 1)
        self.stackedWidget12R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.stackedWidget12R.sizePolicy().hasHeightForWidth())
        self.stackedWidget12R.setSizePolicy(sizePolicy)
        self.stackedWidget12R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget12R.setObjectName("stackedWidget12R")
        self.mosecanvas12R = MplCanvas()
        self.mosecanvas12R.setObjectName("mosecanvas12R")
        self.stackedWidget12R.addWidget(self.mosecanvas12R)
        self.spm1dcanvas12R = MplCanvas()
        self.spm1dcanvas12R.setObjectName("spm1dcanvas12R")
        self.stackedWidget12R.addWidget(self.spm1dcanvas12R)
        self.gridLayout_5.addWidget(self.stackedWidget12R, 6, 2, 1, 1)
        self.stackedWidget02R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.stackedWidget02R.sizePolicy().hasHeightForWidth())
        self.stackedWidget02R.setSizePolicy(sizePolicy)
        self.stackedWidget02R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget02R.setObjectName("stackedWidget02R")
        self.mosecanvas02R = MplCanvas()
        self.mosecanvas02R.setObjectName("mosecanvas02R")
        self.stackedWidget02R.addWidget(self.mosecanvas02R)
        self.spm1dcanvas02R = MplCanvas()
        self.spm1dcanvas02R.setObjectName("spm1dcanvas02R")
        self.stackedWidget02R.addWidget(self.spm1dcanvas02R)
        self.gridLayout_5.addWidget(self.stackedWidget02R, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_rt_side)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.stackedWidget22R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.stackedWidget22R.sizePolicy().hasHeightForWidth())
        self.stackedWidget22R.setSizePolicy(sizePolicy)
        self.stackedWidget22R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget22R.setObjectName("stackedWidget22R")
        self.mosecanvas22R = MplCanvas()
        self.mosecanvas22R.setObjectName("mosecanvas22R")
        self.stackedWidget22R.addWidget(self.mosecanvas22R)
        self.spm1dcanvas22R = MplCanvas()
        self.spm1dcanvas22R.setObjectName("spm1dcanvas22R")
        self.stackedWidget22R.addWidget(self.spm1dcanvas22R)
        self.gridLayout_5.addWidget(self.stackedWidget22R, 10, 2, 1, 1)
        self.stackedWidget11R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget11R.sizePolicy().hasHeightForWidth())
        self.stackedWidget11R.setSizePolicy(sizePolicy)
        self.stackedWidget11R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget11R.setObjectName("stackedWidget11R")
        self.mosecanvas11R = MplCanvas()
        self.mosecanvas11R.setObjectName("mosecanvas11R")
        self.stackedWidget11R.addWidget(self.mosecanvas11R)
        self.spm1dcanvas11R = MplCanvas()
        self.spm1dcanvas11R.setObjectName("spm1dcanvas11R")
        self.stackedWidget11R.addWidget(self.spm1dcanvas11R)
        self.gridLayout_5.addWidget(self.stackedWidget11R, 6, 1, 1, 1)
        self.stackedWidget21R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget21R.sizePolicy().hasHeightForWidth())
        self.stackedWidget21R.setSizePolicy(sizePolicy)
        self.stackedWidget21R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget21R.setObjectName("stackedWidget21R")
        self.mosecanvas21R = MplCanvas()
        self.mosecanvas21R.setObjectName("mosecanvas21R")
        self.stackedWidget21R.addWidget(self.mosecanvas21R)
        self.spm1dcanvas21R = MplCanvas()
        self.spm1dcanvas21R.setObjectName("spm1dcanvas21R")
        self.stackedWidget21R.addWidget(self.spm1dcanvas21R)
        self.gridLayout_5.addWidget(self.stackedWidget21R, 10, 1, 1, 1)
        self.stackedWidget20R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget20R.sizePolicy().hasHeightForWidth())
        self.stackedWidget20R.setSizePolicy(sizePolicy)
        self.stackedWidget20R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget20R.setObjectName("stackedWidget20R")
        self.mosecanvas20R = MplCanvas()
        self.mosecanvas20R.setObjectName("mosecanvas20R")
        self.stackedWidget20R.addWidget(self.mosecanvas20R)
        self.spm1dcanvas20R = MplCanvas()
        self.spm1dcanvas20R.setObjectName("spm1dcanvas20R")
        self.stackedWidget20R.addWidget(self.spm1dcanvas20R)
        self.gridLayout_5.addWidget(self.stackedWidget20R, 10, 0, 1, 1)
        self.stackedWidget01R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget01R.sizePolicy().hasHeightForWidth())
        self.stackedWidget01R.setSizePolicy(sizePolicy)
        self.stackedWidget01R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget01R.setObjectName("stackedWidget01R")
        self.mosecanvas01R = MplCanvas()
        self.mosecanvas01R.setObjectName("mosecanvas01R")
        self.stackedWidget01R.addWidget(self.mosecanvas01R)
        self.spm1dcanvas01R = MplCanvas()
        self.spm1dcanvas01R.setObjectName("spm1dcanvas01R")
        self.stackedWidget01R.addWidget(self.spm1dcanvas01R)
        self.gridLayout_5.addWidget(self.stackedWidget01R, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_rt_side)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 8, 0, 1, 1)
        self.stackedWidget10R = QtWidgets.QStackedWidget(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget10R.sizePolicy().hasHeightForWidth())
        self.stackedWidget10R.setSizePolicy(sizePolicy)
        self.stackedWidget10R.setMinimumSize(QtCore.QSize(100, 75))
        self.stackedWidget10R.setObjectName("stackedWidget10R")
        self.mosecanvas10R = MplCanvas()
        self.mosecanvas10R.setObjectName("mosecanvas10R")
        self.stackedWidget10R.addWidget(self.mosecanvas10R)
        self.spm1dcanvas10R = MplCanvas()
        self.spm1dcanvas10R.setObjectName("spm1dcanvas10R")
        self.stackedWidget10R.addWidget(self.spm1dcanvas10R)
        self.gridLayout_5.addWidget(self.stackedWidget10R, 6, 0, 1, 1)
        self.joint1R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint1R.sizePolicy().hasHeightForWidth())
        self.joint1R.setSizePolicy(sizePolicy)
        self.joint1R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint1R.setObjectName("joint1R")
        self.gridLayout_5.addWidget(self.joint1R, 7, 1, 1, 2)
        self.joint2R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint2R.sizePolicy().hasHeightForWidth())
        self.joint2R.setSizePolicy(sizePolicy)
        self.joint2R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint2R.setObjectName("joint2R")
        self.gridLayout_5.addWidget(self.joint2R, 11, 1, 1, 2)
        self.datacanvas12R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.datacanvas12R.sizePolicy().hasHeightForWidth())
        self.datacanvas12R.setSizePolicy(sizePolicy)
        self.datacanvas12R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas12R.setObjectName("datacanvas12R")
        self.gridLayout_5.addWidget(self.datacanvas12R, 5, 2, 1, 1)
        self.datacanvas01R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas01R.sizePolicy().hasHeightForWidth())
        self.datacanvas01R.setSizePolicy(sizePolicy)
        self.datacanvas01R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas01R.setObjectName("datacanvas01R")
        self.gridLayout_5.addWidget(self.datacanvas01R, 1, 1, 1, 1)
        self.datacanvas00R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas00R.sizePolicy().hasHeightForWidth())
        self.datacanvas00R.setSizePolicy(sizePolicy)
        self.datacanvas00R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas00R.setObjectName("datacanvas00R")
        self.gridLayout_5.addWidget(self.datacanvas00R, 1, 0, 1, 1)
        self.datacanvas11R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas11R.sizePolicy().hasHeightForWidth())
        self.datacanvas11R.setSizePolicy(sizePolicy)
        self.datacanvas11R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas11R.setObjectName("datacanvas11R")
        self.gridLayout_5.addWidget(self.datacanvas11R, 5, 1, 1, 1)
        self.datacanvas02R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.datacanvas02R.sizePolicy().hasHeightForWidth())
        self.datacanvas02R.setSizePolicy(sizePolicy)
        self.datacanvas02R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas02R.setObjectName("datacanvas02R")
        self.gridLayout_5.addWidget(self.datacanvas02R, 1, 2, 1, 1)
        self.datacanvas22R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.datacanvas22R.sizePolicy().hasHeightForWidth())
        self.datacanvas22R.setSizePolicy(sizePolicy)
        self.datacanvas22R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas22R.setObjectName("datacanvas22R")
        self.gridLayout_5.addWidget(self.datacanvas22R, 9, 2, 1, 1)
        self.datacanvas10R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas10R.sizePolicy().hasHeightForWidth())
        self.datacanvas10R.setSizePolicy(sizePolicy)
        self.datacanvas10R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas10R.setObjectName("datacanvas10R")
        self.gridLayout_5.addWidget(self.datacanvas10R, 5, 0, 1, 1)
        self.joint0R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.joint0R.sizePolicy().hasHeightForWidth())
        self.joint0R.setSizePolicy(sizePolicy)
        self.joint0R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint0R.setAutoFillBackground(True)
        self.joint0R.setObjectName("joint0R")
        self.gridLayout_5.addWidget(self.joint0R, 3, 1, 1, 2)
        self.datacanvas20R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas20R.sizePolicy().hasHeightForWidth())
        self.datacanvas20R.setSizePolicy(sizePolicy)
        self.datacanvas20R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas20R.setObjectName("datacanvas20R")
        self.gridLayout_5.addWidget(self.datacanvas20R, 9, 0, 1, 1)
        self.datacanvas21R = MplCanvas(self.widget_rt_side)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas21R.sizePolicy().hasHeightForWidth())
        self.datacanvas21R.setSizePolicy(sizePolicy)
        self.datacanvas21R.setMinimumSize(QtCore.QSize(100, 75))
        self.datacanvas21R.setObjectName("datacanvas21R")
        self.gridLayout_5.addWidget(self.datacanvas21R, 9, 1, 1, 1)
        self.label_flexR = QtWidgets.QLabel(self.widget_rt_side)
        self.label_flexR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flexR.setObjectName("label_flexR")
        self.gridLayout_5.addWidget(self.label_flexR, 0, 0, 1, 1)
        self.label_addR = QtWidgets.QLabel(self.widget_rt_side)
        self.label_addR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_addR.setObjectName("label_addR")
        self.gridLayout_5.addWidget(self.label_addR, 0, 1, 1, 1)
        self.label_rotR = QtWidgets.QLabel(self.widget_rt_side)
        self.label_rotR.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rotR.setObjectName("label_rotR")
        self.gridLayout_5.addWidget(self.label_rotR, 0, 2, 1, 1)
        self.gridLayout_5.setRowStretch(1, 3)
        self.gridLayout_5.setRowStretch(2, 3)
        self.gridLayout_5.setRowStretch(3, 1)
        self.gridLayout_5.setRowStretch(5, 3)
        self.gridLayout_5.setRowStretch(6, 3)
        self.gridLayout_5.setRowStretch(7, 1)
        self.gridLayout_5.setRowStretch(9, 3)
        self.gridLayout_5.setRowStretch(10, 3)
        self.gridLayout_5.setRowStretch(11, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.three_columns_layout.addWidget(self.widget_rt_side, 0, 0, 3, 1)
        self.label_image_src = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_image_src.sizePolicy().hasHeightForWidth())
        self.label_image_src.setSizePolicy(sizePolicy)
        self.label_image_src.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_src.setWordWrap(True)
        self.label_image_src.setOpenExternalLinks(True)
        self.label_image_src.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_image_src.setObjectName("label_image_src")
        self.three_columns_layout.addWidget(self.label_image_src, 2, 1, 1, 1)
        self.skeletonlabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeletonlabel.sizePolicy().hasHeightForWidth())
        self.skeletonlabel.setSizePolicy(sizePolicy)
        self.skeletonlabel.setPixmap(QtGui.QPixmap(":/images/res/RTLT_legSelected.png"))
        self.skeletonlabel.setScaledContents(True)
        self.skeletonlabel.setObjectName("skeletonlabel")
        self.skeleton_gridLayout = QtWidgets.QGridLayout(self.skeletonlabel)
        self.skeleton_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.skeleton_gridLayout.setSpacing(0)
        self.skeleton_gridLayout.setObjectName("skeleton_gridLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_1R = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_1R.sizePolicy().hasHeightForWidth())
        self.pushButton_1R.setSizePolicy(sizePolicy)
        self.pushButton_1R.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_1R.setText("")
        self.pushButton_1R.setObjectName("pushButton_1R")
        self.gridLayout.addWidget(self.pushButton_1R, 2, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.pushButton_2R = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_2R.sizePolicy().hasHeightForWidth())
        self.pushButton_2R.setSizePolicy(sizePolicy)
        self.pushButton_2R.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_2R.setText("")
        self.pushButton_2R.setObjectName("pushButton_2R")
        self.gridLayout.addWidget(self.pushButton_2R, 3, 0, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.pushButton_2L = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_2L.sizePolicy().hasHeightForWidth())
        self.pushButton_2L.setSizePolicy(sizePolicy)
        self.pushButton_2L.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_2L.setText("")
        self.pushButton_2L.setObjectName("pushButton_2L")
        self.gridLayout.addWidget(self.pushButton_2L, 3, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pushButton_1L = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_1L.sizePolicy().hasHeightForWidth())
        self.pushButton_1L.setSizePolicy(sizePolicy)
        self.pushButton_1L.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_1L.setText("")
        self.pushButton_1L.setObjectName("pushButton_1L")
        self.gridLayout.addWidget(self.pushButton_1L, 2, 1, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pushButton_0R = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_0R.sizePolicy().hasHeightForWidth())
        self.pushButton_0R.setSizePolicy(sizePolicy)
        self.pushButton_0R.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_0R.setText("")
        self.pushButton_0R.setObjectName("pushButton_0R")
        self.gridLayout.addWidget(self.pushButton_0R, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pushButton_0L = RoundCirclePushButton(self.skeletonlabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_0L.sizePolicy().hasHeightForWidth())
        self.pushButton_0L.setSizePolicy(sizePolicy)
        self.pushButton_0L.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_0L.setText("")
        self.pushButton_0L.setObjectName("pushButton_0L")
        self.gridLayout.addWidget(self.pushButton_0L, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.setColumnMinimumWidth(0, 100)
        self.gridLayout.setColumnMinimumWidth(1, 100)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 3)
        self.gridLayout.setRowStretch(3, 2)
        self.skeleton_gridLayout.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.three_columns_layout.addWidget(self.skeletonlabel, 1, 1, 1, 1)
        self.label_study = QtWidgets.QLabel(self.centralwidget)
        self.label_study.setObjectName("label_study")
        self.three_columns_layout.addWidget(self.label_study, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.three_columns_layout.setRowStretch(1, 20)
        self.centralwidget_gridLayout.addLayout(self.three_columns_layout, 0, 0, 1, 1)
        ui_GaitAnalysisWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ui_GaitAnalysisWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1489, 36))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuPre_vs_post = QtWidgets.QMenu(self.menuAnalysis)
        self.menuPre_vs_post.setObjectName("menuPre_vs_post")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuClear = QtWidgets.QMenu(self.menuView)
        self.menuClear.setObjectName("menuClear")
        ui_GaitAnalysisWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ui_GaitAnalysisWindow)
        self.statusbar.setObjectName("statusbar")
        ui_GaitAnalysisWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ui_GaitAnalysisWindow)
        self.toolBar.setObjectName("toolBar")
        ui_GaitAnalysisWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.legend_dock_widget = QtWidgets.QDockWidget(ui_GaitAnalysisWindow)
        self.legend_dock_widget.setFloating(False)
        self.legend_dock_widget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.legend_dock_widget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.legend_dock_widget.setObjectName("legend_dock_widget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.legend_widget_contents_layout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.legend_widget_contents_layout.setObjectName("legend_widget_contents_layout")
        self.legend_data_groupbox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.legend_data_groupbox.setObjectName("legend_data_groupbox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.legend_data_groupbox)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.legend_data_panel = MplCanvas(self.legend_data_groupbox)
        self.legend_data_panel.setObjectName("legend_data_panel")
        self.gridLayout_8.addWidget(self.legend_data_panel, 0, 0, 1, 1)
        self.legend_widget_contents_layout.addWidget(self.legend_data_groupbox)
        self.legend_heatmap_groupbox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.legend_heatmap_groupbox.setObjectName("legend_heatmap_groupbox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.legend_heatmap_groupbox)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.legend_heatmap_panel = MplCanvas(self.legend_heatmap_groupbox)
        self.legend_heatmap_panel.setObjectName("legend_heatmap_panel")
        self.gridLayout_9.addWidget(self.legend_heatmap_panel, 1, 0, 1, 1)
        self.label_analysis = AnalysisLabel(self.legend_heatmap_groupbox)
        self.label_analysis.setObjectName("label_analysis")
        self.gridLayout_9.addWidget(self.label_analysis, 0, 0, 1, 1)
        self.legend_widget_contents_layout.addWidget(self.legend_heatmap_groupbox)
        self.legend_dock_widget.setWidget(self.dockWidgetContents)
        ui_GaitAnalysisWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.legend_dock_widget)
        self.action_open_before_intervension = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_open_before_intervension.setObjectName("action_open_before_intervension")
        self.action_open_after_surgery_data = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_open_after_surgery_data.setObjectName("action_open_after_surgery_data")
        self.action_specify_normal_standard = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_specify_normal_standard.setObjectName("action_specify_normal_standard")
        self.action_Exit = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.actionKinematics = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionKinematics.setCheckable(True)
        self.actionKinematics.setObjectName("actionKinematics")
        self.actionMoments = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionMoments.setCheckable(True)
        self.actionMoments.setObjectName("actionMoments")
        self.actionRight_Side = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionRight_Side.setCheckable(True)
        self.actionRight_Side.setObjectName("actionRight_Side")
        self.actionLeft_Side = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionLeft_Side.setCheckable(True)
        self.actionLeft_Side.setObjectName("actionLeft_Side")
        self.actionPaired = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPaired.setObjectName("actionPaired")
        self.actionTwo_Sample = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionTwo_Sample.setObjectName("actionTwo_Sample")
        self.actionPre_vs_Reference = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPre_vs_Reference.setObjectName("actionPre_vs_Reference")
        self.actionPost_vs_Ref = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPost_vs_Ref.setObjectName("actionPost_vs_Ref")
        self.actionNextView = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionNextView.setObjectName("actionNextView")
        self.actionPre_and_Post_Vs_Ref = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPre_and_Post_Vs_Ref.setObjectName("actionPre_and_Post_Vs_Ref")
        self.action_clear_all = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_clear_all.setObjectName("action_clear_all")
        self.action_clear_analysis = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_clear_analysis.setObjectName("action_clear_analysis")
        self.action_view_ligand = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_view_ligand.setCheckable(True)
        self.action_view_ligand.setObjectName("action_view_ligand")
        self.menu_File.addAction(self.action_specify_normal_standard)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_open_before_intervension)
        self.menu_File.addAction(self.action_open_after_surgery_data)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menuPre_vs_post.addAction(self.actionPaired)
        self.menuPre_vs_post.addAction(self.actionTwo_Sample)
        self.menuAnalysis.addAction(self.menuPre_vs_post.menuAction())
        self.menuAnalysis.addAction(self.actionPre_vs_Reference)
        self.menuAnalysis.addAction(self.actionPost_vs_Ref)
        self.menuAnalysis.addAction(self.actionPre_and_Post_Vs_Ref)
        self.menuAnalysis.addSeparator()
        self.menuClear.addAction(self.action_clear_all)
        self.menuClear.addAction(self.action_clear_analysis)
        self.menuView.addAction(self.actionKinematics)
        self.menuView.addAction(self.actionMoments)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRight_Side)
        self.menuView.addAction(self.actionLeft_Side)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNextView)
        self.menuView.addAction(self.menuClear.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.action_view_ligand)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.action_specify_normal_standard)
        self.toolBar.addAction(self.action_open_before_intervension)
        self.toolBar.addAction(self.action_open_after_surgery_data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNextView)

        self.retranslateUi(ui_GaitAnalysisWindow)
        self.stackedWidget21L.setCurrentIndex(1)
        self.stackedWidget12L.setCurrentIndex(1)
        self.stackedWidget01L.setCurrentIndex(1)
        self.stackedWidget02L.setCurrentIndex(1)
        self.stackedWidget00L.setCurrentIndex(1)
        self.stackedWidget22L.setCurrentIndex(1)
        self.stackedWidget10L.setCurrentIndex(1)
        self.stackedWidget11L.setCurrentIndex(1)
        self.stackedWidget20L.setCurrentIndex(1)
        self.stackedWidget00R.setCurrentIndex(1)
        self.stackedWidget12R.setCurrentIndex(1)
        self.stackedWidget02R.setCurrentIndex(1)
        self.stackedWidget22R.setCurrentIndex(1)
        self.stackedWidget11R.setCurrentIndex(1)
        self.stackedWidget21R.setCurrentIndex(1)
        self.stackedWidget20R.setCurrentIndex(1)
        self.stackedWidget01R.setCurrentIndex(1)
        self.stackedWidget10R.setCurrentIndex(1)
        self.actionLeft_Side.toggled['bool'].connect(self.widget_lt_side.setVisible)
        self.actionRight_Side.toggled['bool'].connect(self.widget_rt_side.setVisible)
        self.action_view_ligand.toggled['bool'].connect(self.legend_dock_widget.setVisible)
        self.legend_dock_widget.visibilityChanged['bool'].connect(self.action_view_ligand.setChecked)
        QtCore.QMetaObject.connectSlotsByName(ui_GaitAnalysisWindow)

    def retranslateUi(self, ui_GaitAnalysisWindow):
        _translate = QtCore.QCoreApplication.translate
        ui_GaitAnalysisWindow.setWindowTitle(_translate("ui_GaitAnalysisWindow", "Gait Analysis"))
        self.label_addL.setText(_translate("ui_GaitAnalysisWindow", "Add. / Abduction"))
        self.label_rotL.setText(_translate("ui_GaitAnalysisWindow", "Int. / Ext. rotation"))
        self.label_flexL.setText(_translate("ui_GaitAnalysisWindow", "Flex. / Extension"))
        self.label_flexR.setText(_translate("ui_GaitAnalysisWindow", "Flex. / Extension"))
        self.label_addR.setText(_translate("ui_GaitAnalysisWindow", "Add. / Abduction"))
        self.label_rotR.setText(_translate("ui_GaitAnalysisWindow", "Int. / Ext. rotation"))
        self.label_image_src.setText(_translate("ui_GaitAnalysisWindow", "<html><head/><body><p>Skeleton image from <a href=\"https://ieeexplore.ieee.org/abstract/document/4352056\"><span style=\" text-decoration: underline; color:#0000ff;\">(S. L. Delp et al. 2007)</span></a></p></body></html>"))
        self.label_study.setText(_translate("ui_GaitAnalysisWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Kinematics</span> (deg) / <span style=\" font-weight:600;\">Moments</span> (Nm/kg)</p></body></html>"))
        self.menu_File.setTitle(_translate("ui_GaitAnalysisWindow", "&File"))
        self.menuAnalysis.setTitle(_translate("ui_GaitAnalysisWindow", "&Analysis"))
        self.menuPre_vs_post.setTitle(_translate("ui_GaitAnalysisWindow", "Pre vs. post"))
        self.menuView.setTitle(_translate("ui_GaitAnalysisWindow", "View"))
        self.menuClear.setTitle(_translate("ui_GaitAnalysisWindow", "Clear"))
        self.toolBar.setWindowTitle(_translate("ui_GaitAnalysisWindow", "toolBar"))
        self.legend_dock_widget.setWindowTitle(_translate("ui_GaitAnalysisWindow", "Legend"))
        self.legend_data_groupbox.setTitle(_translate("ui_GaitAnalysisWindow", "Data"))
        self.legend_heatmap_groupbox.setTitle(_translate("ui_GaitAnalysisWindow", "Analysis"))
        self.label_analysis.setText(_translate("ui_GaitAnalysisWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Analysis Name</span></p><p><span style=\" font-weight:600;\">SPM{t}</span> / <span style=\" font-weight:600;\">Colorbar {t}</span></p><p><span style=\" font-weight:600;\">Colorbar{T</span><span style=\" font-weight:600; vertical-align:super;\">2</span><span style=\" font-weight:600;\">}</span></p></body></html>"))
        self.action_open_before_intervension.setText(_translate("ui_GaitAnalysisWindow", "&Open Before surgery data..."))
        self.action_open_after_surgery_data.setText(_translate("ui_GaitAnalysisWindow", "Open &After surgery data..."))
        self.action_specify_normal_standard.setText(_translate("ui_GaitAnalysisWindow", "Specify &Reference"))
        self.action_Exit.setText(_translate("ui_GaitAnalysisWindow", "&Exit"))
        self.actionKinematics.setText(_translate("ui_GaitAnalysisWindow", "Kinematics"))
        self.actionMoments.setText(_translate("ui_GaitAnalysisWindow", "Moments"))
        self.actionRight_Side.setText(_translate("ui_GaitAnalysisWindow", "Right Side"))
        self.actionLeft_Side.setText(_translate("ui_GaitAnalysisWindow", "Left Side"))
        self.actionPaired.setText(_translate("ui_GaitAnalysisWindow", "Paired"))
        self.actionPaired.setToolTip(_translate("ui_GaitAnalysisWindow", "Pre vs. Post (Paired)"))
        self.actionTwo_Sample.setText(_translate("ui_GaitAnalysisWindow", "Two Sample"))
        self.actionTwo_Sample.setToolTip(_translate("ui_GaitAnalysisWindow", "Pre vs. Post (Two Sample)"))
        self.actionPre_vs_Reference.setText(_translate("ui_GaitAnalysisWindow", "Pre vs. Ref..."))
        self.actionPost_vs_Ref.setText(_translate("ui_GaitAnalysisWindow", "Post vs. Ref..."))
        self.actionNextView.setText(_translate("ui_GaitAnalysisWindow", "Plot / Heat map"))
        self.actionNextView.setToolTip(_translate("ui_GaitAnalysisWindow", "NextView (SPM1d, MoSE)"))
        self.actionPre_and_Post_Vs_Ref.setText(_translate("ui_GaitAnalysisWindow", "Pre and Post vs. Ref"))
        self.action_clear_all.setText(_translate("ui_GaitAnalysisWindow", "All"))
        self.action_clear_all.setToolTip(_translate("ui_GaitAnalysisWindow", "Clear both data and analysis result"))
        self.action_clear_analysis.setText(_translate("ui_GaitAnalysisWindow", "Analysis"))
        self.action_clear_analysis.setToolTip(_translate("ui_GaitAnalysisWindow", "Clear the analysis results"))
        self.action_view_ligand.setText(_translate("ui_GaitAnalysisWindow", "Ligand"))

from spmclient.ui.gui.xml.analysislabel import AnalysisLabel
from spmclient.ui.gui.xml.mplcanvas import MplCanvas
from spmclient.ui.gui.xml.roundcirclepushbutton import RoundCirclePushButton
from . import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_GaitAnalysisWindow = QtWidgets.QMainWindow()
    ui = Ui_ui_GaitAnalysisWindow()
    ui.setupUi(ui_GaitAnalysisWindow)
    ui_GaitAnalysisWindow.show()
    sys.exit(app.exec_())

