# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_gait_analysis_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ui_GaitAnalysisWindow(object):
    def setupUi(self, ui_GaitAnalysisWindow):
        ui_GaitAnalysisWindow.setObjectName("ui_GaitAnalysisWindow")
        ui_GaitAnalysisWindow.setWindowModality(QtCore.Qt.WindowModal)
        ui_GaitAnalysisWindow.resize(1336, 777)
        ui_GaitAnalysisWindow.setProperty("visible_hip", False)
        ui_GaitAnalysisWindow.setProperty("visible_knee", False)
        ui_GaitAnalysisWindow.setProperty("visible_ankle", False)
        ui_GaitAnalysisWindow.setProperty("show_colormap", False)
        self.centralwidget = QtWidgets.QWidget(ui_GaitAnalysisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.skeletonlabel = QtWidgets.QLabel(self.centralwidget)
        self.skeletonlabel.setGeometry(QtCore.QRect(570, 0, 191, 681))
        self.skeletonlabel.setText("")
        self.skeletonlabel.setPixmap(QtGui.QPixmap(":/images/res/RTLT_legSelected.png"))
        self.skeletonlabel.setScaledContents(True)
        self.skeletonlabel.setObjectName("skeletonlabel")
        self.pushButton = RoundCirclePushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 290, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = RoundCirclePushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 440, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = RoundCirclePushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 580, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = RoundCirclePushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 290, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = RoundCirclePushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 580, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = RoundCirclePushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(660, 440, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frameL = QtWidgets.QFrame(self.centralwidget)
        self.frameL.setGeometry(QtCore.QRect(770, 0, 561, 711))
        self.frameL.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameL.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameL.setObjectName("frameL")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.frameL)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 0, 544, 688))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayoutL = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayoutL.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutL.setSpacing(2)
        self.verticalLayoutL.setObjectName("verticalLayoutL")
        self.horizontalLayout0L = QtWidgets.QHBoxLayout()
        self.horizontalLayout0L.setObjectName("horizontalLayout0L")
        spacerItem = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout0L.addItem(spacerItem)
        self.verticalLayout00_L = QtWidgets.QVBoxLayout()
        self.verticalLayout00_L.setObjectName("verticalLayout00_L")
        self.datacanvas00L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas00L.sizePolicy().hasHeightForWidth())
        self.datacanvas00L.setSizePolicy(sizePolicy)
        self.datacanvas00L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas00L.setObjectName("datacanvas00L")
        self.verticalLayout00_L.addWidget(self.datacanvas00L)
        self.stackedWidget00L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget00L.sizePolicy().hasHeightForWidth())
        self.stackedWidget00L.setSizePolicy(sizePolicy)
        self.stackedWidget00L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget00L.setObjectName("stackedWidget00L")
        self.mosecanvas00L = MplCanvas()
        self.mosecanvas00L.setObjectName("mosecanvas00L")
        self.stackedWidget00L.addWidget(self.mosecanvas00L)
        self.spm1dcanvas00L = MplCanvas()
        self.spm1dcanvas00L.setObjectName("spm1dcanvas00L")
        self.stackedWidget00L.addWidget(self.spm1dcanvas00L)
        self.verticalLayout00_L.addWidget(self.stackedWidget00L)
        self.horizontalLayout0L.addLayout(self.verticalLayout00_L)
        self.verticalLayout01_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout01_2.setObjectName("verticalLayout01_2")
        self.datacanvas01L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas01L.sizePolicy().hasHeightForWidth())
        self.datacanvas01L.setSizePolicy(sizePolicy)
        self.datacanvas01L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas01L.setObjectName("datacanvas01L")
        self.verticalLayout01_2.addWidget(self.datacanvas01L)
        self.stackedWidget01L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget01L.sizePolicy().hasHeightForWidth())
        self.stackedWidget01L.setSizePolicy(sizePolicy)
        self.stackedWidget01L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget01L.setObjectName("stackedWidget01L")
        self.mosecanvas01L = MplCanvas()
        self.mosecanvas01L.setObjectName("mosecanvas01L")
        self.stackedWidget01L.addWidget(self.mosecanvas01L)
        self.spm1dcanvas01L = MplCanvas()
        self.spm1dcanvas01L.setObjectName("spm1dcanvas01L")
        self.stackedWidget01L.addWidget(self.spm1dcanvas01L)
        self.verticalLayout01_2.addWidget(self.stackedWidget01L)
        self.horizontalLayout0L.addLayout(self.verticalLayout01_2)
        self.verticalLayout00_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout00_4.setObjectName("verticalLayout00_4")
        self.datacanvas02L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas02L.sizePolicy().hasHeightForWidth())
        self.datacanvas02L.setSizePolicy(sizePolicy)
        self.datacanvas02L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas02L.setObjectName("datacanvas02L")
        self.verticalLayout00_4.addWidget(self.datacanvas02L)
        self.stackedWidget02L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget02L.sizePolicy().hasHeightForWidth())
        self.stackedWidget02L.setSizePolicy(sizePolicy)
        self.stackedWidget02L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget02L.setObjectName("stackedWidget02L")
        self.mosecanvas02L = MplCanvas()
        self.mosecanvas02L.setObjectName("mosecanvas02L")
        self.stackedWidget02L.addWidget(self.mosecanvas02L)
        self.spm1dcanvas02L = MplCanvas()
        self.spm1dcanvas02L.setObjectName("spm1dcanvas02L")
        self.stackedWidget02L.addWidget(self.spm1dcanvas02L)
        self.verticalLayout00_4.addWidget(self.stackedWidget02L)
        self.horizontalLayout0L.addLayout(self.verticalLayout00_4)
        self.verticalLayoutL.addLayout(self.horizontalLayout0L)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.joint0L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint0L.sizePolicy().hasHeightForWidth())
        self.joint0L.setSizePolicy(sizePolicy)
        self.joint0L.setMinimumSize(QtCore.QSize(130, 30))
        self.joint0L.setAutoFillBackground(True)
        self.joint0L.setObjectName("joint0L")
        self.horizontalLayout_3.addWidget(self.joint0L)
        spacerItem1 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayoutL.addLayout(self.horizontalLayout_3)
        self.horizontalLayout1_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1_2.setObjectName("horizontalLayout1_2")
        spacerItem2 = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1_2.addItem(spacerItem2)
        self.verticalLayout10_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout10_2.setObjectName("verticalLayout10_2")
        self.datacanvas10L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas10L.sizePolicy().hasHeightForWidth())
        self.datacanvas10L.setSizePolicy(sizePolicy)
        self.datacanvas10L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas10L.setObjectName("datacanvas10L")
        self.verticalLayout10_2.addWidget(self.datacanvas10L)
        self.stackedWidget10L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget10L.sizePolicy().hasHeightForWidth())
        self.stackedWidget10L.setSizePolicy(sizePolicy)
        self.stackedWidget10L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget10L.setObjectName("stackedWidget10L")
        self.mosecanvas10L = MplCanvas()
        self.mosecanvas10L.setObjectName("mosecanvas10L")
        self.stackedWidget10L.addWidget(self.mosecanvas10L)
        self.spm1dcanvas10L = MplCanvas()
        self.spm1dcanvas10L.setObjectName("spm1dcanvas10L")
        self.stackedWidget10L.addWidget(self.spm1dcanvas10L)
        self.verticalLayout10_2.addWidget(self.stackedWidget10L)
        self.horizontalLayout1_2.addLayout(self.verticalLayout10_2)
        self.verticalLayout11_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout11_2.setObjectName("verticalLayout11_2")
        self.datacanvas11L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas11L.sizePolicy().hasHeightForWidth())
        self.datacanvas11L.setSizePolicy(sizePolicy)
        self.datacanvas11L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas11L.setObjectName("datacanvas11L")
        self.verticalLayout11_2.addWidget(self.datacanvas11L)
        self.stackedWidget11L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget11L.sizePolicy().hasHeightForWidth())
        self.stackedWidget11L.setSizePolicy(sizePolicy)
        self.stackedWidget11L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget11L.setObjectName("stackedWidget11L")
        self.mosecanvas11L = MplCanvas()
        self.mosecanvas11L.setObjectName("mosecanvas11L")
        self.stackedWidget11L.addWidget(self.mosecanvas11L)
        self.spm1dcanvas11L = MplCanvas()
        self.spm1dcanvas11L.setObjectName("spm1dcanvas11L")
        self.stackedWidget11L.addWidget(self.spm1dcanvas11L)
        self.verticalLayout11_2.addWidget(self.stackedWidget11L)
        self.horizontalLayout1_2.addLayout(self.verticalLayout11_2)
        self.verticalLayout12_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout12_2.setObjectName("verticalLayout12_2")
        self.datacanvas12L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas12L.sizePolicy().hasHeightForWidth())
        self.datacanvas12L.setSizePolicy(sizePolicy)
        self.datacanvas12L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas12L.setObjectName("datacanvas12L")
        self.verticalLayout12_2.addWidget(self.datacanvas12L)
        self.stackedWidget12L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget12L.sizePolicy().hasHeightForWidth())
        self.stackedWidget12L.setSizePolicy(sizePolicy)
        self.stackedWidget12L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget12L.setObjectName("stackedWidget12L")
        self.mosecanvas12L = MplCanvas()
        self.mosecanvas12L.setObjectName("mosecanvas12L")
        self.stackedWidget12L.addWidget(self.mosecanvas12L)
        self.spm1dcanvas12L = MplCanvas()
        self.spm1dcanvas12L.setObjectName("spm1dcanvas12L")
        self.stackedWidget12L.addWidget(self.spm1dcanvas12L)
        self.verticalLayout12_2.addWidget(self.stackedWidget12L)
        self.horizontalLayout1_2.addLayout(self.verticalLayout12_2)
        self.verticalLayoutL.addLayout(self.horizontalLayout1_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.joint1L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint1L.sizePolicy().hasHeightForWidth())
        self.joint1L.setSizePolicy(sizePolicy)
        self.joint1L.setMinimumSize(QtCore.QSize(130, 30))
        self.joint1L.setObjectName("joint1L")
        self.horizontalLayout_5.addWidget(self.joint1L)
        spacerItem3 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayoutL.addLayout(self.horizontalLayout_5)
        self.horizontalLayout2_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2_2.setObjectName("horizontalLayout2_2")
        spacerItem4 = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2_2.addItem(spacerItem4)
        self.verticalLayout20_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout20_2.setObjectName("verticalLayout20_2")
        self.datacanvas20L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas20L.sizePolicy().hasHeightForWidth())
        self.datacanvas20L.setSizePolicy(sizePolicy)
        self.datacanvas20L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas20L.setObjectName("datacanvas20L")
        self.verticalLayout20_2.addWidget(self.datacanvas20L)
        self.stackedWidget20L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget20L.sizePolicy().hasHeightForWidth())
        self.stackedWidget20L.setSizePolicy(sizePolicy)
        self.stackedWidget20L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget20L.setObjectName("stackedWidget20L")
        self.mosecanvas20L = MplCanvas()
        self.mosecanvas20L.setObjectName("mosecanvas20L")
        self.stackedWidget20L.addWidget(self.mosecanvas20L)
        self.spm1dcanvas20L = MplCanvas()
        self.spm1dcanvas20L.setObjectName("spm1dcanvas20L")
        self.stackedWidget20L.addWidget(self.spm1dcanvas20L)
        self.verticalLayout20_2.addWidget(self.stackedWidget20L)
        self.horizontalLayout2_2.addLayout(self.verticalLayout20_2)
        self.verticalLayout21_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout21_2.setObjectName("verticalLayout21_2")
        self.datacanvas21L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas21L.sizePolicy().hasHeightForWidth())
        self.datacanvas21L.setSizePolicy(sizePolicy)
        self.datacanvas21L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas21L.setObjectName("datacanvas21L")
        self.verticalLayout21_2.addWidget(self.datacanvas21L)
        self.stackedWidget21L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget21L.sizePolicy().hasHeightForWidth())
        self.stackedWidget21L.setSizePolicy(sizePolicy)
        self.stackedWidget21L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget21L.setObjectName("stackedWidget21L")
        self.mosecanvas21L = MplCanvas()
        self.mosecanvas21L.setObjectName("mosecanvas21L")
        self.stackedWidget21L.addWidget(self.mosecanvas21L)
        self.spm1dcanvas21L = MplCanvas()
        self.spm1dcanvas21L.setObjectName("spm1dcanvas21L")
        self.stackedWidget21L.addWidget(self.spm1dcanvas21L)
        self.verticalLayout21_2.addWidget(self.stackedWidget21L)
        self.horizontalLayout2_2.addLayout(self.verticalLayout21_2)
        self.verticalLayout22_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout22_2.setObjectName("verticalLayout22_2")
        self.datacanvas22L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas22L.sizePolicy().hasHeightForWidth())
        self.datacanvas22L.setSizePolicy(sizePolicy)
        self.datacanvas22L.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas22L.setObjectName("datacanvas22L")
        self.verticalLayout22_2.addWidget(self.datacanvas22L)
        self.stackedWidget22L = QtWidgets.QStackedWidget(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget22L.sizePolicy().hasHeightForWidth())
        self.stackedWidget22L.setSizePolicy(sizePolicy)
        self.stackedWidget22L.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget22L.setObjectName("stackedWidget22L")
        self.mosecanvas22L = MplCanvas()
        self.mosecanvas22L.setObjectName("mosecanvas22L")
        self.stackedWidget22L.addWidget(self.mosecanvas22L)
        self.spm1dcanvas22L = MplCanvas()
        self.spm1dcanvas22L.setObjectName("spm1dcanvas22L")
        self.stackedWidget22L.addWidget(self.spm1dcanvas22L)
        self.verticalLayout22_2.addWidget(self.stackedWidget22L)
        self.horizontalLayout2_2.addLayout(self.verticalLayout22_2)
        self.verticalLayoutL.addLayout(self.horizontalLayout2_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.joint2L = MplCanvas(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint2L.sizePolicy().hasHeightForWidth())
        self.joint2L.setSizePolicy(sizePolicy)
        self.joint2L.setMinimumSize(QtCore.QSize(130, 30))
        self.joint2L.setObjectName("joint2L")
        self.horizontalLayout_6.addWidget(self.joint2L)
        spacerItem5 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayoutL.addLayout(self.horizontalLayout_6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 680, 191, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.frameR = QtWidgets.QFrame(self.centralwidget)
        self.frameR.setGeometry(QtCore.QRect(-1, 0, 561, 711))
        self.frameR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameR.setObjectName("frameR")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frameR)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 544, 688))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout0 = QtWidgets.QHBoxLayout()
        self.horizontalLayout0.setObjectName("horizontalLayout0")
        self.verticalLayout00 = QtWidgets.QVBoxLayout()
        self.verticalLayout00.setObjectName("verticalLayout00")
        self.datacanvas00R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas00R.sizePolicy().hasHeightForWidth())
        self.datacanvas00R.setSizePolicy(sizePolicy)
        self.datacanvas00R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas00R.setObjectName("datacanvas00R")
        self.verticalLayout00.addWidget(self.datacanvas00R)
        self.stackedWidget00R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget00R.sizePolicy().hasHeightForWidth())
        self.stackedWidget00R.setSizePolicy(sizePolicy)
        self.stackedWidget00R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget00R.setObjectName("stackedWidget00R")
        self.mosecanvas00R = MplCanvas()
        self.mosecanvas00R.setObjectName("mosecanvas00R")
        self.stackedWidget00R.addWidget(self.mosecanvas00R)
        self.spm1dcanvas00R = MplCanvas()
        self.spm1dcanvas00R.setObjectName("spm1dcanvas00R")
        self.stackedWidget00R.addWidget(self.spm1dcanvas00R)
        self.verticalLayout00.addWidget(self.stackedWidget00R)
        self.horizontalLayout0.addLayout(self.verticalLayout00)
        self.verticalLayout01 = QtWidgets.QVBoxLayout()
        self.verticalLayout01.setObjectName("verticalLayout01")
        self.datacanvas01R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas01R.sizePolicy().hasHeightForWidth())
        self.datacanvas01R.setSizePolicy(sizePolicy)
        self.datacanvas01R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas01R.setObjectName("datacanvas01R")
        self.verticalLayout01.addWidget(self.datacanvas01R)
        self.stackedWidget01R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget01R.sizePolicy().hasHeightForWidth())
        self.stackedWidget01R.setSizePolicy(sizePolicy)
        self.stackedWidget01R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget01R.setObjectName("stackedWidget01R")
        self.mosecanvas01R = MplCanvas()
        self.mosecanvas01R.setObjectName("mosecanvas01R")
        self.stackedWidget01R.addWidget(self.mosecanvas01R)
        self.spm1dcanvas01R = MplCanvas()
        self.spm1dcanvas01R.setObjectName("spm1dcanvas01R")
        self.stackedWidget01R.addWidget(self.spm1dcanvas01R)
        self.verticalLayout01.addWidget(self.stackedWidget01R)
        self.horizontalLayout0.addLayout(self.verticalLayout01)
        self.verticalLayout00_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout00_2.setObjectName("verticalLayout00_2")
        self.datacanvas02R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas02R.sizePolicy().hasHeightForWidth())
        self.datacanvas02R.setSizePolicy(sizePolicy)
        self.datacanvas02R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas02R.setObjectName("datacanvas02R")
        self.verticalLayout00_2.addWidget(self.datacanvas02R)
        self.stackedWidget02R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget02R.sizePolicy().hasHeightForWidth())
        self.stackedWidget02R.setSizePolicy(sizePolicy)
        self.stackedWidget02R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget02R.setObjectName("stackedWidget02R")
        self.mosecanvas02R = MplCanvas()
        self.mosecanvas02R.setObjectName("mosecanvas02R")
        self.stackedWidget02R.addWidget(self.mosecanvas02R)
        self.spm1dcanvas02R = MplCanvas()
        self.spm1dcanvas02R.setObjectName("spm1dcanvas02R")
        self.stackedWidget02R.addWidget(self.spm1dcanvas02R)
        self.verticalLayout00_2.addWidget(self.stackedWidget02R)
        self.horizontalLayout0.addLayout(self.verticalLayout00_2)
        spacerItem6 = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout0.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout0)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.joint0R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint0R.sizePolicy().hasHeightForWidth())
        self.joint0R.setSizePolicy(sizePolicy)
        self.joint0R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint0R.setAutoFillBackground(True)
        self.joint0R.setObjectName("joint0R")
        self.horizontalLayout.addWidget(self.joint0R)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.verticalLayout10 = QtWidgets.QVBoxLayout()
        self.verticalLayout10.setObjectName("verticalLayout10")
        self.datacanvas10R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas10R.sizePolicy().hasHeightForWidth())
        self.datacanvas10R.setSizePolicy(sizePolicy)
        self.datacanvas10R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas10R.setObjectName("datacanvas10R")
        self.verticalLayout10.addWidget(self.datacanvas10R)
        self.stackedWidget10R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget10R.sizePolicy().hasHeightForWidth())
        self.stackedWidget10R.setSizePolicy(sizePolicy)
        self.stackedWidget10R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget10R.setObjectName("stackedWidget10R")
        self.mosecanvas10R = MplCanvas()
        self.mosecanvas10R.setObjectName("mosecanvas10R")
        self.stackedWidget10R.addWidget(self.mosecanvas10R)
        self.spm1dcanvas10R = MplCanvas()
        self.spm1dcanvas10R.setObjectName("spm1dcanvas10R")
        self.stackedWidget10R.addWidget(self.spm1dcanvas10R)
        self.verticalLayout10.addWidget(self.stackedWidget10R)
        self.horizontalLayout1.addLayout(self.verticalLayout10)
        self.verticalLayout11 = QtWidgets.QVBoxLayout()
        self.verticalLayout11.setObjectName("verticalLayout11")
        self.datacanvas11R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas11R.sizePolicy().hasHeightForWidth())
        self.datacanvas11R.setSizePolicy(sizePolicy)
        self.datacanvas11R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas11R.setObjectName("datacanvas11R")
        self.verticalLayout11.addWidget(self.datacanvas11R)
        self.stackedWidget11R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget11R.sizePolicy().hasHeightForWidth())
        self.stackedWidget11R.setSizePolicy(sizePolicy)
        self.stackedWidget11R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget11R.setObjectName("stackedWidget11R")
        self.mosecanvas11R = MplCanvas()
        self.mosecanvas11R.setObjectName("mosecanvas11R")
        self.stackedWidget11R.addWidget(self.mosecanvas11R)
        self.spm1dcanvas11R = MplCanvas()
        self.spm1dcanvas11R.setObjectName("spm1dcanvas11R")
        self.stackedWidget11R.addWidget(self.spm1dcanvas11R)
        self.verticalLayout11.addWidget(self.stackedWidget11R)
        self.horizontalLayout1.addLayout(self.verticalLayout11)
        self.verticalLayout12 = QtWidgets.QVBoxLayout()
        self.verticalLayout12.setObjectName("verticalLayout12")
        self.datacanvas12R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas12R.sizePolicy().hasHeightForWidth())
        self.datacanvas12R.setSizePolicy(sizePolicy)
        self.datacanvas12R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas12R.setObjectName("datacanvas12R")
        self.verticalLayout12.addWidget(self.datacanvas12R)
        self.stackedWidget12R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget12R.sizePolicy().hasHeightForWidth())
        self.stackedWidget12R.setSizePolicy(sizePolicy)
        self.stackedWidget12R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget12R.setObjectName("stackedWidget12R")
        self.mosecanvas12R = MplCanvas()
        self.mosecanvas12R.setObjectName("mosecanvas12R")
        self.stackedWidget12R.addWidget(self.mosecanvas12R)
        self.spm1dcanvas12R = MplCanvas()
        self.spm1dcanvas12R.setObjectName("spm1dcanvas12R")
        self.stackedWidget12R.addWidget(self.spm1dcanvas12R)
        self.verticalLayout12.addWidget(self.stackedWidget12R)
        self.horizontalLayout1.addLayout(self.verticalLayout12)
        spacerItem8 = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.joint1R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint1R.sizePolicy().hasHeightForWidth())
        self.joint1R.setSizePolicy(sizePolicy)
        self.joint1R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint1R.setObjectName("joint1R")
        self.horizontalLayout_2.addWidget(self.joint1R)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.verticalLayout20 = QtWidgets.QVBoxLayout()
        self.verticalLayout20.setObjectName("verticalLayout20")
        self.datacanvas20R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas20R.sizePolicy().hasHeightForWidth())
        self.datacanvas20R.setSizePolicy(sizePolicy)
        self.datacanvas20R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas20R.setObjectName("datacanvas20R")
        self.verticalLayout20.addWidget(self.datacanvas20R)
        self.stackedWidget20R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget20R.sizePolicy().hasHeightForWidth())
        self.stackedWidget20R.setSizePolicy(sizePolicy)
        self.stackedWidget20R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget20R.setObjectName("stackedWidget20R")
        self.mosecanvas20R = MplCanvas()
        self.mosecanvas20R.setObjectName("mosecanvas20R")
        self.stackedWidget20R.addWidget(self.mosecanvas20R)
        self.spm1dcanvas20R = MplCanvas()
        self.spm1dcanvas20R.setObjectName("spm1dcanvas20R")
        self.stackedWidget20R.addWidget(self.spm1dcanvas20R)
        self.verticalLayout20.addWidget(self.stackedWidget20R)
        self.horizontalLayout2.addLayout(self.verticalLayout20)
        self.verticalLayout21 = QtWidgets.QVBoxLayout()
        self.verticalLayout21.setObjectName("verticalLayout21")
        self.datacanvas21R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas21R.sizePolicy().hasHeightForWidth())
        self.datacanvas21R.setSizePolicy(sizePolicy)
        self.datacanvas21R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas21R.setObjectName("datacanvas21R")
        self.verticalLayout21.addWidget(self.datacanvas21R)
        self.stackedWidget21R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget21R.sizePolicy().hasHeightForWidth())
        self.stackedWidget21R.setSizePolicy(sizePolicy)
        self.stackedWidget21R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget21R.setObjectName("stackedWidget21R")
        self.mosecanvas21R = MplCanvas()
        self.mosecanvas21R.setObjectName("mosecanvas21R")
        self.stackedWidget21R.addWidget(self.mosecanvas21R)
        self.spm1dcanvas21R = MplCanvas()
        self.spm1dcanvas21R.setObjectName("spm1dcanvas21R")
        self.stackedWidget21R.addWidget(self.spm1dcanvas21R)
        self.verticalLayout21.addWidget(self.stackedWidget21R)
        self.horizontalLayout2.addLayout(self.verticalLayout21)
        self.verticalLayout22 = QtWidgets.QVBoxLayout()
        self.verticalLayout22.setObjectName("verticalLayout22")
        self.datacanvas22R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datacanvas22R.sizePolicy().hasHeightForWidth())
        self.datacanvas22R.setSizePolicy(sizePolicy)
        self.datacanvas22R.setMinimumSize(QtCore.QSize(100, 80))
        self.datacanvas22R.setObjectName("datacanvas22R")
        self.verticalLayout22.addWidget(self.datacanvas22R)
        self.stackedWidget22R = QtWidgets.QStackedWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget22R.sizePolicy().hasHeightForWidth())
        self.stackedWidget22R.setSizePolicy(sizePolicy)
        self.stackedWidget22R.setMinimumSize(QtCore.QSize(0, 80))
        self.stackedWidget22R.setObjectName("stackedWidget22R")
        self.mosecanvas22R = MplCanvas()
        self.mosecanvas22R.setObjectName("mosecanvas22R")
        self.stackedWidget22R.addWidget(self.mosecanvas22R)
        self.spm1dcanvas22R = MplCanvas()
        self.spm1dcanvas22R.setObjectName("spm1dcanvas22R")
        self.stackedWidget22R.addWidget(self.spm1dcanvas22R)
        self.verticalLayout22.addWidget(self.stackedWidget22R)
        self.horizontalLayout2.addLayout(self.verticalLayout22)
        spacerItem10 = QtWidgets.QSpacerItem(100, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem11 = QtWidgets.QSpacerItem(400, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.joint2R = MplCanvas(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joint2R.sizePolicy().hasHeightForWidth())
        self.joint2R.setSizePolicy(sizePolicy)
        self.joint2R.setMinimumSize(QtCore.QSize(130, 30))
        self.joint2R.setObjectName("joint2R")
        self.horizontalLayout_4.addWidget(self.joint2R)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.skeletonlabel.raise_()
        self.frameR.raise_()
        self.frameL.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.label.raise_()
        ui_GaitAnalysisWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ui_GaitAnalysisWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1336, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuPre_vs_post = QtWidgets.QMenu(self.menuAnalysis)
        self.menuPre_vs_post.setObjectName("menuPre_vs_post")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuClear = QtWidgets.QMenu(self.menuView)
        self.menuClear.setObjectName("menuClear")
        ui_GaitAnalysisWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ui_GaitAnalysisWindow)
        self.statusbar.setObjectName("statusbar")
        ui_GaitAnalysisWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ui_GaitAnalysisWindow)
        self.toolBar.setObjectName("toolBar")
        ui_GaitAnalysisWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_open_before_intervension = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_open_before_intervension.setObjectName("action_open_before_intervension")
        self.action_open_after_surgery_data = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_open_after_surgery_data.setObjectName("action_open_after_surgery_data")
        self.action_specify_normal_standard = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_specify_normal_standard.setObjectName("action_specify_normal_standard")
        self.action_Exit = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.actionKinematics = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionKinematics.setCheckable(True)
        self.actionKinematics.setObjectName("actionKinematics")
        self.actionMoments = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionMoments.setCheckable(True)
        self.actionMoments.setObjectName("actionMoments")
        self.actionRight_Side = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionRight_Side.setCheckable(True)
        self.actionRight_Side.setObjectName("actionRight_Side")
        self.actionLeft_Side = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionLeft_Side.setCheckable(True)
        self.actionLeft_Side.setObjectName("actionLeft_Side")
        self.actionPaired = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPaired.setObjectName("actionPaired")
        self.actionTwo_Sample = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionTwo_Sample.setObjectName("actionTwo_Sample")
        self.actionPre_vs_Reference = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPre_vs_Reference.setObjectName("actionPre_vs_Reference")
        self.actionPost_vs_Ref = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPost_vs_Ref.setObjectName("actionPost_vs_Ref")
        self.actionNextView = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionNextView.setObjectName("actionNextView")
        self.actionPre_and_Post_Vs_Ref = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.actionPre_and_Post_Vs_Ref.setObjectName("actionPre_and_Post_Vs_Ref")
        self.action_clear_all = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_clear_all.setObjectName("action_clear_all")
        self.action_clear_analysis = QtWidgets.QAction(ui_GaitAnalysisWindow)
        self.action_clear_analysis.setObjectName("action_clear_analysis")
        self.menu_File.addAction(self.action_specify_normal_standard)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_open_before_intervension)
        self.menu_File.addAction(self.action_open_after_surgery_data)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menuPre_vs_post.addAction(self.actionPaired)
        self.menuPre_vs_post.addAction(self.actionTwo_Sample)
        self.menuAnalysis.addAction(self.menuPre_vs_post.menuAction())
        self.menuAnalysis.addAction(self.actionPre_vs_Reference)
        self.menuAnalysis.addAction(self.actionPost_vs_Ref)
        self.menuAnalysis.addAction(self.actionPre_and_Post_Vs_Ref)
        self.menuAnalysis.addSeparator()
        self.menuClear.addAction(self.action_clear_all)
        self.menuClear.addAction(self.action_clear_analysis)
        self.menuView.addAction(self.actionKinematics)
        self.menuView.addAction(self.actionMoments)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionRight_Side)
        self.menuView.addAction(self.actionLeft_Side)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNextView)
        self.menuView.addAction(self.menuClear.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.action_specify_normal_standard)
        self.toolBar.addAction(self.action_open_before_intervension)
        self.toolBar.addAction(self.action_open_after_surgery_data)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNextView)

        self.retranslateUi(ui_GaitAnalysisWindow)
        self.stackedWidget00L.setCurrentIndex(1)
        self.stackedWidget01L.setCurrentIndex(1)
        self.stackedWidget02L.setCurrentIndex(1)
        self.stackedWidget10L.setCurrentIndex(1)
        self.stackedWidget11L.setCurrentIndex(1)
        self.stackedWidget12L.setCurrentIndex(1)
        self.stackedWidget20L.setCurrentIndex(1)
        self.stackedWidget21L.setCurrentIndex(1)
        self.stackedWidget22L.setCurrentIndex(1)
        self.stackedWidget00R.setCurrentIndex(1)
        self.stackedWidget01R.setCurrentIndex(1)
        self.stackedWidget02R.setCurrentIndex(1)
        self.stackedWidget10R.setCurrentIndex(1)
        self.stackedWidget11R.setCurrentIndex(1)
        self.stackedWidget12R.setCurrentIndex(1)
        self.stackedWidget20R.setCurrentIndex(1)
        self.stackedWidget21R.setCurrentIndex(1)
        self.stackedWidget22R.setCurrentIndex(1)
        self.actionRight_Side.triggered['bool'].connect(self.frameR.setVisible)
        self.actionLeft_Side.triggered['bool'].connect(self.frameL.setVisible)
        QtCore.QMetaObject.connectSlotsByName(ui_GaitAnalysisWindow)

    def retranslateUi(self, ui_GaitAnalysisWindow):
        _translate = QtCore.QCoreApplication.translate
        ui_GaitAnalysisWindow.setWindowTitle(_translate("ui_GaitAnalysisWindow", "Gait Analysis"))
        self.label.setText(_translate("ui_GaitAnalysisWindow", "Skeleton image from<br><a href=\"https://ieeexplore.ieee.org/abstract/document/4352056\">(S. L. Delp et al. 2007)</a>"))
        self.menu_File.setTitle(_translate("ui_GaitAnalysisWindow", "&File"))
        self.menuAnalysis.setTitle(_translate("ui_GaitAnalysisWindow", "&Analysis"))
        self.menuPre_vs_post.setTitle(_translate("ui_GaitAnalysisWindow", "Pre vs. post"))
        self.menuView.setTitle(_translate("ui_GaitAnalysisWindow", "View"))
        self.menuClear.setTitle(_translate("ui_GaitAnalysisWindow", "Clear"))
        self.toolBar.setWindowTitle(_translate("ui_GaitAnalysisWindow", "toolBar"))
        self.action_open_before_intervension.setText(_translate("ui_GaitAnalysisWindow", "&Open Before surgery data..."))
        self.action_open_after_surgery_data.setText(_translate("ui_GaitAnalysisWindow", "Open &After surgery data..."))
        self.action_specify_normal_standard.setText(_translate("ui_GaitAnalysisWindow", "Specify &Reference"))
        self.action_Exit.setText(_translate("ui_GaitAnalysisWindow", "&Exit"))
        self.actionKinematics.setText(_translate("ui_GaitAnalysisWindow", "Kinematics"))
        self.actionMoments.setText(_translate("ui_GaitAnalysisWindow", "Moments"))
        self.actionRight_Side.setText(_translate("ui_GaitAnalysisWindow", "Right Side"))
        self.actionLeft_Side.setText(_translate("ui_GaitAnalysisWindow", "Left Side"))
        self.actionPaired.setText(_translate("ui_GaitAnalysisWindow", "Paired"))
        self.actionTwo_Sample.setText(_translate("ui_GaitAnalysisWindow", "Two Sample"))
        self.actionPre_vs_Reference.setText(_translate("ui_GaitAnalysisWindow", "Pre vs. Ref..."))
        self.actionPost_vs_Ref.setText(_translate("ui_GaitAnalysisWindow", "Post vs. Ref..."))
        self.actionNextView.setText(_translate("ui_GaitAnalysisWindow", "Plot / Heat map"))
        self.actionNextView.setToolTip(_translate("ui_GaitAnalysisWindow", "NextView (SPM1d, MoSE)"))
        self.actionPre_and_Post_Vs_Ref.setText(_translate("ui_GaitAnalysisWindow", "Pre and Post Vs. Ref"))
        self.action_clear_all.setText(_translate("ui_GaitAnalysisWindow", "All"))
        self.action_clear_all.setToolTip(_translate("ui_GaitAnalysisWindow", "Clear both data and analysis result"))
        self.action_clear_analysis.setText(_translate("ui_GaitAnalysisWindow", "Analysis"))
        self.action_clear_analysis.setToolTip(_translate("ui_GaitAnalysisWindow", "Clear the analysis results"))

from spmclient.ui.gui.xml.mplcanvas import MplCanvas
from spmclient.ui.gui.xml.roundcirclepushbutton import RoundCirclePushButton
from . import res_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui_GaitAnalysisWindow = QtWidgets.QMainWindow()
    ui = Ui_ui_GaitAnalysisWindow()
    ui.setupUi(ui_GaitAnalysisWindow)
    ui_GaitAnalysisWindow.show()
    sys.exit(app.exec_())

