# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\gui\xml\ui_license_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_license_dialog(object):
    def setupUi(self, license_dialog):
        license_dialog.setObjectName("license_dialog")
        license_dialog.resize(493, 621)
        self.gridLayout = QtWidgets.QGridLayout(license_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(license_dialog)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)

        self.retranslateUi(license_dialog)
        QtCore.QMetaObject.connectSlotsByName(license_dialog)

    def retranslateUi(self, license_dialog):
        _translate = QtCore.QCoreApplication.translate
        license_dialog.setWindowTitle(_translate("license_dialog", "Dialog"))
        self.plainTextEdit.setDocumentTitle(_translate("license_dialog", "License"))
        self.plainTextEdit.setPlaceholderText(_translate("license_dialog", "GPL Version 3"))
from spmclient import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    license_dialog = QtWidgets.QDialog()
    ui = Ui_license_dialog()
    ui.setupUi(license_dialog)
    license_dialog.show()
    sys.exit(app.exec_())
