LT_SIDE_CHECKED = 'LT_SIDE_CHECKED'
RT_SIDE_CHECKED = 'RT_SIDE_CHECKED'
KINEMATICS_CHECKED = 'KINEMATICS_CHECKED'
MOMENTS_CHECKED = 'MOMENTS_CHECKED'
ALPHA = 'ALPHA'

MEASUREMENT = 'MEASUREMENT'
MEASUREMENT_KINEMATICS = 'kinematic'
MEASUREMENT_MOMENTS = 'moment'
measurement_folder = ['kinematic', 'moment']

SUBJECT_REF = 'Ref'
SUBJECT_B4 = 'Before Surgery'
SUBJECT_AFTER = 'After Surgery'
subject = [SUBJECT_REF, SUBJECT_B4, SUBJECT_AFTER]
# subject = ['Ref', 'Lam', 'After Surgery']
SIDE_RIGHT = 'R'
SIDE_LEFT = 'L'
side = [SIDE_RIGHT, SIDE_LEFT]
joint = ['Hip', 'Knee', 'Ankle']
dim = ['X', 'Y', 'Z']
measurement_suffix = ['Ang', 'moment']

SUFFIX = 'SUFFIX'  # TODO @deprecated
SUBJECT = 'SUBJECT'
SIDE = 'SIDE'
JOINT = 'JOINT'
DIMENSION = 'DIMENSION'

PRE_VS_REF = 'PRE_VS_REF'
POST_VS_REF = 'POST_VS_REF'
PRE_AND_POST_VS_REF = 'PRE_AND_POST_VS_REF'
PRE_VS_POST_PAIRED = 'PRE_VS_POST_PAIRED'
PRE_VS_POST_TWO_SAMPLE = 'PRE_VS_POST_TWO_SAMPLE'
